default: &default
  facebook_id: '1703433259924920'
  facebook_secret_key: '79d2009183d601fb772c0d10e799f1c6'
  twitter_consumer_key: 'R3gLDhAZYk5TJXa8Nc8ROvN7J'
  twitter_consumer_secret: 'ZVFjgUHAs0PR8ByGujFaktoJlUXVKH4x8a4VFeFVfUggMOVBBa'

development:
  secret_key_base: a94ca2ddcfca304fb089d83fb2e67e393f316224ca81d36f22207eaf24d590b1ee6d57a8492a4846d99a7a147f1cb12a75e451d83726dcfd7e333ee73b4bd437
  <<: *default

test:
  secret_key_base: 66c008150171222a84b18ef68e593b017354e94825cd30cfe8f6c7ae2d4bf08ace6fbf8a0c8850d55e41e94830aae5eb89fe60e5fa341f23828d9a860fcaa411
  <<: *default

# 本番環境では環境変数にKEYを登録します
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_id: <%= ENV["FACEBOOK_APP_ID"] %>
  facebook_secret_key: <%= ENV["FACEBOOK_APP_SECRET"] %>
  twitter_consumer_key: <%= ENV["TWITTER_CONSUMER_KEY"] %>
  twitter_consumer_secret: <%= ENV["TWITTER_CONSUMER_SECRET"] %>